# Generated by Django 3.1.4 on 2020-12-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo_link',
            field=models.CharField(default='https://www.flaticon.com/svg/static/icons/svg/2964/2964063.svg', max_length=200),
        ),
    ]
