# Generated by Django 3.1.4 on 2020-12-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
