# Generated by Django 3.1.4 on 2020-12-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_feed', '0002_source_logo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='logo_link',
            field=models.CharField(max_length=200),
        ),
    ]
