# Generated by Django 3.1.4 on 2020-12-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_feed', '0002_remove_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='classified',
        ),
    ]
