# Generated by Django 3.1.4 on 2020-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_userbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='folder',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
