# Generated by Django 3.1.4 on 2020-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_usersource_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersource',
            name='folder',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
