# Generated by Django 3.1.4 on 2020-12-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20201213_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersource',
            name='folder',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
