# Generated by Django 3.1.4 on 2020-12-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20201213_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersource',
            name='folder',
        ),
    ]
