# Generated by Django 3.1.4 on 2020-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_usersource_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='folder',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
